/* generated_scripts.h — forward declarations for all scene functions.
   Auto-generated by choice4snes; do not edit. */
#ifndef GENERATED_SCRIPTS_H
#define GENERATED_SCRIPTS_H
#include "vn_engine.h"
void *VS_startup(void);
#endif
