/*
 * main.c  —  choice4snes entry point
 * Auto-generated by choice4snes; do not edit.
 */
#include <snes.h>
#include "vn_engine.h"
#include "generated_scripts.h"

int main(void) {
    VN_init();

    scriptFunction scene = VS_startup;
    while (scene) {
        scene = (scriptFunction)scene();
    }
    return 0;
}
